### ISSUE TITLE
Unicode characters in data not rendered correctly

### ISSUE THREAD

**Issue by AxelTerizaki** [mnyrop/wax_tasks#75]
**Describe the bug**
Pages rendered through pagemaster do not seem to read unicode characters properly.

**To Reproduce**
1. Use this shortened data file : [karas.json.txt](https://github.com/mnyrop/wax_tasks/files/2379373/karas.json.txt)
2. Use this collection definition : 
```
  fr/karas:
    output: true
    source: karas.json
    layout: kara_fr
```
3. I don't suppose you need the layout but just in case here it is : [kara_fr.html.txt](https://github.com/mnyrop/wax_tasks/files/2379363/kara_fr.html.txt)
4. Run pagemaster task on this collection

**Expected behavior**
On the rendered file (in fr/karas folder) you'll find that the songwriter field is incorrectly rendered.

**Screenshots**
How it's rendered : 
```
songwriter: Ha├»m Saban,Shuki Levy
```
How it's in the JSON file : 
```
[{"pid":"13cb4509-6cb4-43e4-a1ad-417d6ffb75d0","kid":"13cb4509-6cb4-43e4-a1ad-417d6ffb75d0","title":"Ulis 31","duration":67,"audiogain":-1.52,"year":"1981","subfile":"BRE - Uchuu Densetsu Ulysses 31 - OP - Ulis 31.ass","karafile":"BRE - Uchuu Densetsu Ulysses 31 - OP - Ulis 31.kara","mediasize":10832121,"mediafile":"BRE - Uchuu Densetsu Ulysses 31 - OP - Ulis 31.mp4","dateadded":1531602456,"datemodif":1531602456,"order":"","serie":"Uchuu Densetsu Ulysses 31","NORM_serie":"Uchuu Densetsu Ulysses 31","singer":"Jean Luc Roudaut,Nolwenn Corbel","type":"TYPE_OP","creator":"TMS ENTERTAINMENT","lang":"bre","author":"Aeden","tags":"TAG_ANIME,TAG_TVSHOW","songwriter":"Haïm Saban,Shuki Levy"}]
```

As you can see, Haïm Saban's name is correct in the JSON. It's encoded in UTF-8 on my end (at least according to Visual Studio Code...)

**Desktop (please complete the following information):**
 - Jekyll version 3.8.3
 - Ruby 2.4.1p111
 - OS: Windows 7

Thanks in advance for fixing this :)

**Comment by mnyrop** [comment]
I'm not able reproduce the error... I think there might be unicode processing differences on windows. Let me know if you find anything out?

![](http://oi66.tinypic.com/152l24x.jpg)

**Comment by AxelTerizaki** [comment]
What's weird is that with my previous plugin it worked well. Besides, when using standard Jekyll collection processing to make lists (like, in the singers.html page in https://lab.shelter.moe/karaokemugen/sites/mugen-site/tree/wax_task ) characters are rendered correctly. You can try to fetch the website from that branche and `jekyll build` it, then check the singers.html rendered there.

I'll test it under Linux to see if I can reproduce it, I suppose.

**Comment by AxelTerizaki** [comment]
I confirm this happens only on Windows, which is a little annoying but not a big problem (my site is built from a Linux box) 

I tested it under  another Windows box. Under WSL in Windows 10 (Ubuntu for Windows) it works fine though, the render is correct.)

As I said, this didn't happen with other plugins, or even with Jekyll's standard collection parsing.

**Comment by mnyrop** [comment]
Got it, thanks for the additional info. I'll close this ticket but will keep an eye out for what might be the difference. Feel free to link to the other plugins you're referencing and I'll try to do some recon.

**Comment by AxelTerizaki** [comment]
On the current live version of the website (http://mugen.karaokes.moe/en) I'm using datapage_gen : https://github.com/avillafiorita/jekyll-datapage_gen
