### ISSUE TITLE
Diacritics normalization not working

### ISSUE THREAD

**Issue by AxelTerizaki** [mnyrop/wax_tasks#84]
**Describe the bug**
When generating pages via `wax:pagemaster` characters with diacritics are removed. They should be normalized instead. You wrote in issue mnyrop/pagemaster#13 that it was working in wax_tasks, but I don't think it does.

**To Reproduce**
1. Use the following collection definition : 
```
  en/series:
    output: true
    source: series.json
    layout: series_en
```
2. Use the following JSON file as input : 
[series.json.txt](https://github.com/mnyrop/wax_tasks/files/2441066/series.json.txt)

3. Launch wax:pagemaster rake task on that.
4. Go to the generated .md files directory and see for yourself that an item like "Gankutsuô" is rendered as `gankutsu.md`, making linking to those pages difficult. Note that inside, the permalink field is also incorrect.

**Expected behavior**
Item "Gankutsuô" should have a file called `gankutsuo.md`

**Desktop (please complete the following information):**
 - OS: Windows or Linux, same problem
 - Version: Jekyll 3.8.4, wax_tasks 0.3.2

Thanks in advance!

**Comment by AxelTerizaki** [comment]
Hmmm, I just put `gem "wax_tasks", "1.0.0-beta"` in my gemfile and it installed 1.0.0-pre-beta (not sure if it's the same version?) 

And sadly, diacritics still aren't working. I retried with the same dataset as in the issue and the generated files still remove any letter with an accent.

Has this been working on Linux? Note that I still have an issue on Windows, where any accent or special character isn't properly rendered.

Example: `Gankutsuô`  is rendered in the generated .md file as `Gankutsu├┤`  which might explain why it doesn't write the correct filename. I'll have to test it out under Linux. (our CI/CD is on a Linux box but we dev and test under Windows so this is still a bit troublesome)

**Comment by AxelTerizaki** [comment]
I replaced the line in the gemfile and I get that during bundle install : 

```
Using wax_tasks 1.0.0.pre.beta from https://github.com/mnyrop/wax_tasks.git (at diacritic-slug-patch@9306572)
```

So I'm guessing it's the right version. However, when I run wax:pagemaster on the series.json in the issue, I still get a `gankutsu.md` file instead of `gankutsuo.md`

For now as a workaround I create the JSON where the pid property is a deburred/normalized string (without any diacritics) so it works well that way, but having that workaround isn't ideal.

**Comment by AxelTerizaki** [comment]
Sorry, can't edit from my current browser for some reason, just wanted to add that I did a `bundle install --force` to make sure I got the right version.

**Comment by mnyrop** [comment]
<img width="652" alt="screen shot 2018-11-12 at 10 02 08 am" src="https://user-images.githubusercontent.com/25022284/48355513-35e23200-e662-11e8-8d25-48be31dd6952.png">
<img width="360" alt="screen shot 2018-11-12 at 10 02 18 am" src="https://user-images.githubusercontent.com/25022284/48355520-38dd2280-e662-11e8-82a0-a57fe96d3a1f.png">


I added it to the spec test data and produced the desired result, so I'm not sure. Did you delete the folder of markdown pages to make sure they are regenerated? Pagemaster skips over them if it sees they already exist.

In practice though,  persistent identifiers shouldn't have diacritics precisely because they will be handled differently by different systems. I'll still include the patch, but would recommend you use a custom rake task to pre-process your PIDs.

**Comment by AxelTerizaki** [comment]
Yep, I'm pretty sure I deleted the created markdown files before trying to regenerate them.

I believe it works on Linux, but on Windows it doesn't, perhaps because as I said ealirer, there's another issue with how diacritics are rendered. Then perhaps the character isn't normalized as it should simply because it can't find an equivalent.

`ô` seems to be read as `├┤` when I use wax:tasks, so obviously it won't be able to tell which character it should replace it with...

**Comment by mnyrop** [comment]
wax_tasks gives explicit / hardcoded instructions for normalizing diacritics:

https://github.com/mnyrop/wax_tasks/blob/8064c7f1f1714bc858c830ec0f84ebd30f8b7dde/lib/wax_tasks/utils.rb#L106-L110

So i don't know why that would be the case
