### ISSUE TITLE
Slugification of _ characters

### ISSUE THREAD

**Issue by AxelTerizaki** [mnyrop/wax_tasks#94]
As I'm trying to import my dataset, some of the indexes have a _ character in them. When wax:pagemaster writes the filename, it keeps the underscore instead of replacing it with a -.

On my pages, to determine the URL for items in a list, I use the `slugify: "latin"` liquid template filter, which translates _ into -.

If Jekyll and wax:pagemaster had the same rules when slugifying, it'd make things easier (as a workaround, I can replace _s with -s but still :) )

**Comment by mnyrop** [comment]
This would be a breaking change for other sites. Unless something changes, it probably won't be changed.

**Comment by AxelTerizaki** [comment]
Just to clarify, the workaround is to replace -s with _s after I slugify a string, so it actually finds the correct URL, not the other way around like I said in my previous post (it was a mistake)

**Comment by AxelTerizaki** [comment]
Ah, just saw your reply.

So let's take this the other way around : 

How can I safely know what the URL of an item in a collection is ? I see it creates a permalink field in the .md file, but there's no way, from let's say another page entirely, to safely link to the first page if I can't rely on the `slugify` liquid template filter. 

The previous plugin I was using create a liquid filter tag to use its own slugification rules on a string so I could be sure I was getting the exact same filename, maybe that's something that could be done instead if you're not using the same rules as in the `slugify` filter jekyll uses?
